msgid ""
msgstr ""
"Project-Id-Version: red-discordbot\n"
"POT-Creation-Date: 2018-02-19 03:59+UTC\n"
"PO-Revision-Date: 2018-02-25 21:32-0500\n"
"Last-Translator: Kowlin <boxedpp@gmail.com>\n"
"Language-Team: Spanish\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: ENCODING\n"
"Generated-By: pygettext.py 1.5\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Generator: crowdin.com\n"
"X-Crowdin-Project: red-discordbot\n"
"X-Crowdin-Language: es-ES\n"
"X-Crowdin-File: /core/locales/messages.pot\n"
"Language: es_ES\n"

#: ../cog_manager.py:309
msgid "Install Path: {}\n\n"
msgstr "Ruta de instalación: {}\n\n"

#: ../cog_manager.py:325
msgid "That path does not exist or does not point to a valid directory."
msgstr "Esa ruta es no existe o no apunta a un directorio válido."

#: ../cog_manager.py:334
msgid "Path successfully added."
msgstr "Ruta añadida exitósamente."

#: ../cog_manager.py:347
msgid "That is an invalid path number."
msgstr "Número de ruta inválido."

#: ../cog_manager.py:351
msgid "Path successfully removed."
msgstr "Ruta eliminada exitósamente."

#: ../cog_manager.py:367
msgid "Invalid 'from' index."
msgstr "Índice 'from' no válido."

#: ../cog_manager.py:373
msgid "Invalid 'to' index."
msgstr "Índice 'to' no válido."

#: ../cog_manager.py:377
msgid "Paths reordered."
msgstr "Rutas reordenadas."

#: ../cog_manager.py:395
msgid "That path does not exist."
msgstr "Ruta inexistente."

#: ../cog_manager.py:399
msgid "The bot will install new cogs to the `{}` directory."
msgstr "El bot instalará nuevos cogs en el directorio '{}'."

#: ../core_commands.py:225 ../core_commands.py:266
msgid "No module by that name was found in any cog path."
msgstr "Ningún módulo con ese nombre fue encontrado en ninguna ruta."

#: ../core_commands.py:240
msgid "Failed to load package. Check your console or logs for details."
msgstr "Error al cargar el paquete. Revise su consola o bitácoras para más detalles."

#: ../core_commands.py:244 ../core_commands.py:253 ../core_commands.py:285
#: ../core_commands.py:374 ../core_commands.py:462 ../core_commands.py:476
msgid "Done."
msgstr "Listo."

#: ../core_commands.py:255
msgid "That extension is not loaded."
msgstr "La extensión no está cargada."

#: ../core_commands.py:282
msgid "Failed to reload package. Check your console or logs for details."
msgstr "Error al recargar el paquete. Revise su consola o bitácoras para más detalles."

#: ../core_commands.py:295
msgid "Shutting down... "
msgstr "Apagando... "

#: ../core_commands.py:310
msgid "Restarting..."
msgstr "Reiniciando..."

#: ../core_commands.py:347
msgid "The admin role for this guild has been set."
msgstr "El rol de administrador para este gremio ha sido configurado."

#: ../core_commands.py:355
msgid "The mod role for this guild has been set."
msgstr "El rol de moderador para este gremio ha sido configurado."

#: ../core_commands.py:368
msgid "Failed. Remember that you can edit my avatar up to two times a hour. The URL must be a direct link to a JPG / PNG."
msgstr "Error. Recuerde que puede editar mi avatar hasta dos veces por hora. La URL debe ser un enlace directo a un JPG o PNG."

#: ../core_commands.py:372
msgid "JPG / PNG format only."
msgstr "Únicamente formatos JPG o PNG."

#: ../core_commands.py:387
msgid "Game set."
msgstr "Juego configurado."

#: ../core_commands.py:399
msgid "Listening set."
msgstr "Escuchando junto."

#: ../core_commands.py:411
msgid "Watching set."
msgstr "Viendo junto."

#: ../core_commands.py:440
msgid "Status changed to %s."
msgstr "Estado cambiado a %s."

#: ../core_commands.py:471
msgid "Failed to change name. Remember that you can only do it up to 2 times an hour. Use nicknames if you need frequent changes. `{}set nickname`"
msgstr "No se pudo cambiar el nombre. Recuerde que śolo se puede hacer hasta 2 veces por hora. Utilizar sobrenombres si cambios más frecuentes son necesarios. `{}set nickname`"

#: ../core_commands.py:486
msgid "I lack the permissions to change my own nickname."
msgstr "No tengo permisos para cambiar mi propio sobrenombre."

#: ../core_commands.py:500 ../core_commands.py:513
msgid "Prefix set."
msgstr "Prefijo configurado."

#: ../core_commands.py:509
msgid "Guild prefixes have been reset."
msgstr "Prefijos de gremio han sido restaurados."

#: ../core_commands.py:532
msgid "\n"
"Verification token:"
msgstr "\n"
"Código de verificación:"

#: ../core_commands.py:535
msgid "Remember:\n"
msgstr "Recuerda:\n"

#: ../core_commands.py:538
msgid "I have printed a one-time token in the console. Copy and paste it here to confirm you are the owner."
msgstr "He impreso un código de uso único en la consola. Copie y péguelo acá para confirmar que es el dueño."

#: ../core_commands.py:546
msgid "The set owner request has timed out."
msgstr "El tiempo de espera para configuración de dueño se ha agotado."

#: ../core_commands.py:552
msgid "You have been set as owner."
msgstr "Ha sido configurado como dueño."

#: ../core_commands.py:554
msgid "Invalid token."
msgstr "Código inválido."

#: ../core_commands.py:566
msgid "Locale has been set."
msgstr "Configuración regional establecida."

#: ../core_commands.py:580
msgid "Done. Sentry logging is now enabled."
msgstr "Hecho. Ya está habilitado el inicio del robot."

#: ../core_commands.py:583
msgid "Done. Sentry logging is now disabled."
msgstr "Hecho. Ya está deshabilitado el inicio del robot."

#: ../core_commands.py:593
msgid "User ID: %s"
msgstr "ID de usuario: %s"

#: ../core_commands.py:596
msgid "through DM"
msgstr "a través de MP"

#: ../core_commands.py:598
msgid "from {}"
msgstr "de {}"

#: ../core_commands.py:599
msgid " | Server ID: %s"
msgstr " | ID del servidor: %s"

#: ../core_commands.py:608
msgid "Use `{}dm {} <text>` to reply to this user"
msgstr "Utilice `{}dm {} <texto>` para responder a este usuario"

#: ../core_commands.py:616
msgid "Sent by {} {}"
msgstr "Enviado por {} {}"

#: ../core_commands.py:628
msgid "I cannot send your message, I'm unable to find my owner... *sigh*"
msgstr "No puedo enviar el mensaje, soy incapaz de encontrar a mi dueño... *suspiro*"

#: ../core_commands.py:631
msgid "I'm unable to deliver your message. Sorry."
msgstr "No soy capaz de entregar su mensaje. Lo siento."

#: ../core_commands.py:633
msgid "Your message has been sent."
msgstr "Su mensaje ha sido enviado."

#: ../core_commands.py:647
msgid "Invalid ID or user not found. You can only send messages to people I share a server with."
msgstr "ID o usuario no encontrado. Sólo puede enviar mensajes a personas con quienes comparto un servidor."

#: ../core_commands.py:653
msgid "Owner of %s"
msgstr "Dueño de %s"

#: ../core_commands.py:657
msgid "You can reply to this message with %scontact"
msgstr "Puede responder a este mensaje utilizando %scontact"

#: ../core_commands.py:667
msgid "Sorry, I couldn't deliver your message to %s"
msgstr "Lo siento, no pude enviar su mensaje a %s"

#: ../core_commands.py:670
msgid "Message delivered to %s"
msgstr "Mensaje enviado a %s"

#: ../core_commands.py:690
msgid "User added to whitelist."
msgstr "Usuario añadido a la lista blanca."

#: ../core_commands.py:699
msgid "Whitelisted Users:"
msgstr "Usuarios en lista blanca:"

#: ../core_commands.py:719
msgid "User has been removed from whitelist."
msgstr "El usuario ha sido removido de la lista blanca."

#: ../core_commands.py:721
msgid "User was not in the whitelist."
msgstr "El usuario no estaba en la lista blanca."

#: ../core_commands.py:729
msgid "Whitelist has been cleared."
msgstr "La lista blanca ha sido borrada."

#: ../core_commands.py:746
msgid "You cannot blacklist an owner!"
msgstr "No puedes poner un dueño en la lista negra!"

#: ../core_commands.py:753
msgid "User added to blacklist."
msgstr "Usuario ha añadido a la lista negra."

#: ../core_commands.py:762
msgid "blacklisted Users:"
msgstr "usuarios en la lista negra:"

#: ../core_commands.py:782
msgid "User has been removed from blacklist."
msgstr "El usuario se ha eliminado de la lista negra."

#: ../core_commands.py:784
msgid "User was not in the blacklist."
msgstr "El usuario no estaba en la lista negra."

#: ../core_commands.py:792
msgid "blacklist has been cleared."
msgstr "la lista negra ha sido borrada."

#: ../dev_commands.py:213
msgid "Already running a REPL session in this channel. Exit it with `quit`."
msgstr "Este canal ya está ejecutando una sesión REPL. Salga usando `quit`."

#: ../dev_commands.py:218
msgid "Enter code to execute or evaluate. `exit()` or `quit` to exit."
msgstr "Ingresar código a ejecutar o evaluar. `exit()` o `quit` para salir."

#: ../dev_commands.py:281
msgid "Unexpected error: `{}`"
msgstr "Error inesperado: `{}`"

