Discord.py is updated to 1.2.4 to handle a critical issue with voice connections
